### ISSUE TITLE
Panic invalid memory address nil pointer de reference

### ISSUE THREAD

**Issue by mkunz7** [ryanchapman/go-any-proxy#20]
I'm forcing lots of data through this proxy.

Running dedicated hardware. 
Dell 710 Xeon 5650 24gb ram 

I'm getting hard crashes and a stack trace
As a workaround we've been rebooting the service every 5min.

Here's a small subset of the stack trace.
```
2016/03/07 16:30:05 any_proxy.go:509: : INFO : dial(): ERR: could not connect to 10.0.7.214:443: dial tcp 10.0.7.214:443: no route to host
2016/03/07 16:30:05 any_proxy.go:509: : INFO : dial(): ERR: could not connect to 10.0.7.214:443: dial tcp 10.0.7.214:443: no route to host
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x404b09]

goroutine 6 [running]:
runtime.panic(0x526ce0, 0x6ab6a8)
        /usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.handleDirectConnection(0xc2100002c0, 0xc2100445a0, 0xa, 0x1bb)
        /home/ubuntu/anyproxy/go-any-proxy/any_proxy.go:533 +0x459
main.handleConnection(0xc2100002c0)
        /home/ubuntu/anyproxy/go-any-proxy/any_proxy.go:670 +0x27c
created by main.main
        /home/ubuntu/anyproxy/go-any-proxy/any_proxy.go:349 +0x452

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7fde6ec7d340, 0x72, 0x0)
        /usr/lib/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc210050370, 0x72, 0x7fde6ec7c098, 0xb)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc210050370, 0xb, 0x7fde6ec7c098)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).accept(0xc210050310, 0x5950f0, 0x0, 0x7fde6ec7c098, 0xb)
        /usr/lib/go/src/pkg/net/fd_unix.go:382 +0x2c2
net.(*TCPListener).AcceptTCP(0xc210000138, 0xc210000230, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/tcpsock_posix.go:233 +0x47
main.main()
        /home/ubuntu/anyproxy/go-any-proxy/any_proxy.go:342 +0x35d

goroutine 3 [syscall]:
os/signal.loop()
        /usr/lib/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init<C2><B7>1
        /usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31

goroutine 4 [chan receive]:
main.func<C2><B7>006()
        /home/ubuntu/anyproxy/go-any-proxy/stats.go:259 +0x4d
created by main.setupStats
        /home/ubuntu/anyproxy/go-any-proxy/stats.go:290 +0x101

goroutine 5 [running]:
        goroutine running on other thread; stack unavailable
created by main.main
        /home/ubuntu/anyproxy/go-any-proxy/any_proxy.go:349 +0x452
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x404b09]

goroutine 5 [running]:
runtime.panic(0x526ce0, 0x6ab6a8)
        /usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.handleDirectConnection(0xc2100001f0, 0xc210044500, 0xa, 0x1bb)
        /home/ubuntu/anyproxy/go-any-proxy/any_proxy.go:533 +0x459
main.handleConnection(0xc2100001f0)
        /home/ubuntu/anyproxy/go-any-proxy/any_proxy.go:670 +0x27c
created by main.main
        /home/ubuntu/anyproxy/go-any-proxy/any_proxy.go:349 +0x452
```

**Comment by ryanchapman** [comment]
Hi,

Thanks for reporting this.  Can you try re-pulling from master and re-compiling?   I think it might be fixed.

Thanks
Ryan

**Comment by mkunz7** [comment]
I'll update and try it out in the morning. Thanks for the update :)

**Comment by mkunz7** [comment]
Looks good to me. Haven't had the issue repeat for a few hours.  Thank you.
