### ISSUE TITLE
reverseLookupCache.hostnames need lock

### ISSUE THREAD

**Issue by keminar** [ryanchapman/go-any-proxy#28]
panic:
concurrent map iteration and map write

```
type reverseLookupCache struct {
  hostnames map[string]*cacheEntry
  keys []string
  next int
  mu   sync.Mutex
}
```
lookup and store function add
```
c.mu.Lock()
defer c.mu.Unlock()
```

**Comment by ryanchapman** [comment]
Could you pleaser add a full stack trace of the panic you’re running into?

**Comment by keminar** [comment]
```
package main

import (
	"fmt"
	"time"

	"gitea.com/lunny/log"
)

type cacheEntry struct {
	hostname string
	expires  time.Time
}
type reverseLookupCache struct {
	hostnames map[string]*cacheEntry
	keys      []string
	next      int
}

func NewReverseLookupCache() *reverseLookupCache {
	return &reverseLookupCache{
		hostnames: make(map[string]*cacheEntry),
		keys:      make([]string, 65536),
	}
}
func (c *reverseLookupCache) lookup(ipv4 string) string {
	hit := c.hostnames[ipv4]
	if hit != nil {
		if hit.expires.After(time.Now()) {
			log.Debugf("lookup(): CACHE_HIT")
			return hit.hostname
		} else {
			log.Debugf("lookup(): CACHE_EXPIRED")
			delete(c.hostnames, ipv4)
		}
	} else {
		log.Debugf("lookup(): CACHE_MISS")
	}
	return ""
}
func (c *reverseLookupCache) store(ipv4, hostname string) {
	delete(c.hostnames, c.keys[c.next])
	c.keys[c.next] = ipv4
	c.next = (c.next + 1) & 65535
	c.hostnames[ipv4] = &cacheEntry{hostname: hostname, expires: time.Now().Add(time.Hour)}
}

var gReverseLookupCache *reverseLookupCache

func main() {
	gReverseLookupCache = NewReverseLookupCache()

	for i := 0; i < 10; i++ {
		go func() {
			ipv4 := fmt.Sprintf("test-%d", i)
			hostname := gReverseLookupCache.lookup(ipv4)
			if hostname != "" {
				ipv4 = hostname
			} else {
				val := fmt.Sprintf("val-%d", i)
				gReverseLookupCache.store(ipv4, val)
			}
		}()
	}
}

```

**Comment by keminar** [comment]
```
go: finding gitea.com/lunny/log latest
fatal error: concurrent map read and map write

goroutine 12 [running]:
runtime.throw(0x4cf674, 0x21)
>---/data/opt/go/src/runtime/panic.go:617 +0x72 fp=0xc000031eb0 sp=0xc000031e80 pc=0x428f92
runtime.mapaccess1_faststr(0x4ae680, 0xc0000721b0, 0xc000182090, 0x7, 0x7)
>---/data/opt/go/src/runtime/map_faststr.go:21 +0x469 fp=0xc000031f20 sp=0xc000031eb0 pc=0x40ffe9
main.(*reverseLookupCache).lookup(0xc0000721e0, 0xc000182090, 0x7, 0x1, 0x1)
>---/data/app/golang/src/test.go:27 +0x52 fp=0xc000031f70 sp=0xc000031f20 pc=0x494f22
main.main.func1(0xc000014110)
>---/data/app/golang/src/test.go:56 +0xb3 fp=0xc000031fd8 sp=0xc000031f70 pc=0x4954e3
runtime.goexit()
>---/data/opt/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000031fe0 sp=0xc000031fd8 pc=0x452181
created by main.main
>---/data/app/golang/src/test.go:54 +0xe8
```

**Comment by ryanchapman** [comment]
Thanks for reporting that.  You are indeed correct, that struct needs to be synchronized.  If you have time, could you send in a PR?  If not, I'll take care of it this week.
